"""Graph data model for ArchHub workflows.

A Workflow is a directed acyclic graph (DAG) of Nodes connected by Edges.
Each Node has typed input and output Ports. Workflows are JSON-serializable
so they can be saved, shared, version-controlled, and generated by an LLM.

This is phase 1 — the data layer. There is no canvas UI yet. Workflows are
authored either by capturing a chat conversation (chat_to_workflow.py) or
by handwriting/generating JSON. The executor (executor.py) runs them headless.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional


SCHEMA_VERSION = "1.0"


# ---------------------------------------------------------------------------
class PortType(str, Enum):
    """Type tags for ports. Used for compatibility checking when wiring.

    Type families per ADR-003:
      Primitives   — ANY, STRING, NUMBER, BOOLEAN, OBJECT, LIST
      Bridge       — HOST, DOCUMENT, MODEL, PROJECT
      AI           — PROMPT, MESSAGE, CONVERSATION, TOOL_RESULT, INTENT,
                     COMPLETION
      AEC          — ELEMENT, SELECTION (subsumes WALL/DOOR/etc when LOD
                     differentiation isn't required)
      Files / IO   — FILE, PATH, IMAGE, IFC, CSV
      Geometry     — GEOMETRY (Speckle / Rhino object graph)
      Control      — EXEC (Unreal-style execution pin, white-arrow wire)
                     CRON, TRIGGER, EVENT
    """
    # Primitives
    ANY        = "any"
    STRING     = "string"
    NUMBER     = "number"
    BOOLEAN    = "boolean"
    OBJECT     = "object"
    LIST       = "list"
    # Bridge (ADR-003)
    HOST       = "host"        # one of the AEC host adapters
    DOCUMENT   = "document"    # an opened document inside a host
    MODEL      = "model"       # alias for DOCUMENT in 3D contexts
    PROJECT    = "project"     # a project / firm scope grouping
    # AI
    PROMPT       = "prompt"
    MESSAGE      = "message"
    CONVERSATION = "conversation"
    INTENT       = "intent"
    COMPLETION   = "completion"
    TOOL_RESULT  = "tool_result"
    # AEC entity references
    ELEMENT    = "element"
    SELECTION  = "selection"
    # Files / IO
    FILE       = "file"
    PATH       = "path"
    IMAGE      = "image"
    IFC        = "ifc"
    CSV        = "csv"
    # Geometry
    GEOMETRY   = "geometry"
    # Control flow
    EXEC       = "exec"        # white-arrow execution wire (Unreal pattern)
    CRON       = "cron"
    TRIGGER    = "trigger"
    EVENT      = "event"


@dataclass
class Port:
    name: str
    type: PortType = PortType.ANY
    description: str = ""
    required: bool = False
    default: Any = None
    # ADR-003 additions:
    exec: bool = False         # True = execution pin (draws white arrow)
    multiple: bool = False     # True = input accepts multiple wires

    def to_dict(self) -> dict:
        return {"name": self.name, "type": self.type.value,
                "description": self.description, "required": self.required,
                "default": self.default,
                "exec": self.exec, "multiple": self.multiple}

    @staticmethod
    def from_dict(d: dict) -> "Port":
        return Port(name=d["name"],
                    type=PortType(d.get("type", "any")),
                    description=d.get("description", ""),
                    required=d.get("required", False),
                    default=d.get("default"),
                    exec=bool(d.get("exec", False)),
                    multiple=bool(d.get("multiple", False)))


# ---------------------------------------------------------------------------
@dataclass
class Node:
    id: str                                   # unique within the workflow
    type: str                                 # registered node type, e.g. "llm.complete"
    label: str = ""                           # display label
    config: dict = field(default_factory=dict)        # type-specific config
    inputs: list[Port] = field(default_factory=list)
    outputs: list[Port] = field(default_factory=list)
    position: dict = field(default_factory=lambda: {"x": 0.0, "y": 0.0})

    def to_dict(self) -> dict:
        return {
            "id": self.id, "type": self.type, "label": self.label,
            "config": self.config,
            "inputs":  [p.to_dict() for p in self.inputs],
            "outputs": [p.to_dict() for p in self.outputs],
            "position": self.position,
        }

    @staticmethod
    def from_dict(d: dict) -> "Node":
        return Node(
            id=d["id"], type=d["type"], label=d.get("label", ""),
            config=d.get("config", {}),
            inputs=[Port.from_dict(p) for p in d.get("inputs",  [])],
            outputs=[Port.from_dict(p) for p in d.get("outputs", [])],
            position=d.get("position", {"x": 0.0, "y": 0.0}),
        )


@dataclass
class Edge:
    id: str
    src_node: str
    src_port: str
    dst_node: str
    dst_port: str
    # v1.4 (ADR-003 §"Execution model" + Agent A wire-research):
    # Edges carry runtime data state on disk. The actual `value` lives
    # only in the in-process WireBus to avoid bloating session.graph;
    # `cache_key` lets a re-opened session detect "still fresh".
    cache_key: str = ""
    state: str = "idle"   # idle | flowing | cached | stale | error | upstream_error
    value_preview: str = ""   # repr(value)[:200] for hover tooltip

    def to_dict(self) -> dict:
        return {"id": self.id, "src_node": self.src_node, "src_port": self.src_port,
                "dst_node": self.dst_node, "dst_port": self.dst_port,
                "cache_key": self.cache_key, "state": self.state,
                "value_preview": self.value_preview}

    @staticmethod
    def from_dict(d: dict) -> "Edge":
        return Edge(id=d["id"], src_node=d["src_node"], src_port=d["src_port"],
                    dst_node=d["dst_node"], dst_port=d["dst_port"],
                    cache_key=d.get("cache_key", "") or "",
                    state=d.get("state", "idle") or "idle",
                    value_preview=d.get("value_preview", "") or "")


# ---------------------------------------------------------------------------
@dataclass
class Trigger:
    """How a workflow is fired. Phase 1 supports: manual, cron, speckle_webhook, file_watch."""
    id: str
    type: str                                  # "manual" | "cron" | "speckle_webhook" | "file_watch"
    config: dict = field(default_factory=dict)
    enabled: bool = True

    def to_dict(self) -> dict:
        return asdict(self)

    @staticmethod
    def from_dict(d: dict) -> "Trigger":
        return Trigger(id=d["id"], type=d["type"],
                       config=d.get("config", {}), enabled=d.get("enabled", True))


# ---------------------------------------------------------------------------
@dataclass
class Workflow:
    id: str
    name: str
    description: str = ""
    schema_version: str = SCHEMA_VERSION
    nodes: list[Node] = field(default_factory=list)
    edges: list[Edge] = field(default_factory=list)
    triggers: list[Trigger] = field(default_factory=list)
    inputs: list[Port] = field(default_factory=list)     # workflow-level inputs
    outputs: list[Port] = field(default_factory=list)    # workflow-level outputs
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    # Skill metadata. When `intent` is non-empty, the workflow is discoverable
    # as a Skill: the matcher can pick it for a user prompt, the chat can
    # propose it, and the library shows it under the Skills tab.
    # Empty intent = plain workflow (manual run only).
    metadata: dict = field(default_factory=dict)

    # ---- factory helpers ----
    @staticmethod
    def new(name: str, description: str = "") -> "Workflow":
        return Workflow(id=str(uuid.uuid4()), name=name, description=description,
                        triggers=[Trigger(id=str(uuid.uuid4()), type="manual")])

    # ---- mutation -----------
    def add_node(self, node: Node) -> Node:
        self.nodes.append(node)
        self.updated_at = datetime.now(timezone.utc).isoformat()
        return node

    def add_edge(self, edge: Edge) -> Edge:
        self.edges.append(edge)
        self.updated_at = datetime.now(timezone.utc).isoformat()
        return edge

    def get_node(self, node_id: str) -> Optional[Node]:
        return next((n for n in self.nodes if n.id == node_id), None)

    def edges_into(self, node_id: str) -> list[Edge]:
        return [e for e in self.edges if e.dst_node == node_id]

    def edges_out_of(self, node_id: str) -> list[Edge]:
        return [e for e in self.edges if e.src_node == node_id]

    # ---- serialization -----
    def to_dict(self) -> dict:
        return {
            "id": self.id, "name": self.name, "description": self.description,
            "schema_version": self.schema_version,
            "nodes":    [n.to_dict() for n in self.nodes],
            "edges":    [e.to_dict() for e in self.edges],
            "triggers": [t.to_dict() for t in self.triggers],
            "inputs":   [p.to_dict() for p in self.inputs],
            "outputs":  [p.to_dict() for p in self.outputs],
            "metadata": self.metadata,
            "created_at": self.created_at, "updated_at": self.updated_at,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)

    @staticmethod
    def from_dict(d: dict) -> "Workflow":
        return Workflow(
            id=d["id"], name=d["name"],
            description=d.get("description", ""),
            schema_version=d.get("schema_version", SCHEMA_VERSION),
            nodes=[Node.from_dict(n) for n in d.get("nodes", [])],
            edges=[Edge.from_dict(e) for e in d.get("edges", [])],
            triggers=[Trigger.from_dict(t) for t in d.get("triggers", [])],
            inputs=[Port.from_dict(p) for p in d.get("inputs", [])],
            outputs=[Port.from_dict(p) for p in d.get("outputs", [])],
            metadata=d.get("metadata", {}) or {},
            created_at=d.get("created_at", datetime.now(timezone.utc).isoformat()),
            updated_at=d.get("updated_at", datetime.now(timezone.utc).isoformat()),
        )

    @staticmethod
    def from_json(text: str) -> "Workflow":
        return Workflow.from_dict(json.loads(text))

    @staticmethod
    def load(path: Path) -> "Workflow":
        return Workflow.from_json(Path(path).read_text(encoding="utf-8"))

    def save(self, path: Path) -> None:
        Path(path).write_text(self.to_json(), encoding="utf-8")

    # ---- validation ---------
    def validate(self) -> list[str]:
        """Return a list of errors. Empty list = workflow is valid."""
        errors: list[str] = []
        ids = {n.id for n in self.nodes}
        if len(ids) != len(self.nodes):
            errors.append("Duplicate node ids.")
        for e in self.edges:
            if e.src_node not in ids:
                errors.append(f"Edge {e.id}: src_node '{e.src_node}' missing.")
            if e.dst_node not in ids:
                errors.append(f"Edge {e.id}: dst_node '{e.dst_node}' missing.")
            src = self.get_node(e.src_node) if e.src_node in ids else None
            dst = self.get_node(e.dst_node) if e.dst_node in ids else None
            if src and not any(p.name == e.src_port for p in src.outputs):
                errors.append(f"Edge {e.id}: src_port '{e.src_port}' not on node '{src.id}'.")
            if dst and not any(p.name == e.dst_port for p in dst.inputs):
                errors.append(f"Edge {e.id}: dst_port '{e.dst_port}' not on node '{dst.id}'.")
        # Topo sort to detect cycles
        try:
            self._topo_sort()
        except RuntimeError as ex:
            errors.append(str(ex))
        return errors

    def _topo_sort(self) -> list[str]:
        in_deg = {n.id: 0 for n in self.nodes}
        for e in self.edges:
            if e.dst_node in in_deg:
                in_deg[e.dst_node] += 1
        queue = [nid for nid, d in in_deg.items() if d == 0]
        order: list[str] = []
        while queue:
            nid = queue.pop(0)
            order.append(nid)
            for e in self.edges_out_of(nid):
                in_deg[e.dst_node] -= 1
                if in_deg[e.dst_node] == 0:
                    queue.append(e.dst_node)
        if len(order) != len(self.nodes):
            raise RuntimeError("Cycle detected in workflow graph.")
        return order
